### ISSUE TITLE
SensioInsigt analyse

### ISSUE THREAD

**Issue by vbeauvivre** [easyrdf/easyrdf#198]
Hello
I am interested by your project for further usage on a data portal project. I made an analysis of easyRdf on SensioInsigt code analyse tool.
I tough you could be interested by the result :

https://insight.sensiolabs.com/projects/99f2baa8-ee1e-498a-8a15-d6eb9657075b/analyses/4

This tool reveal some coding error or potential issues for free and offer a great help in quality improvement with simple recommendations.

**Comment by k00ni** [comment]
The link (https://insight.sensiolabs.com/prajects/99f2baa8-ee1e-498a-8a15-d6eb9657075b) isn't working anymore. There is nothing to do here anymore and therefore the issue should be closed.
