### ISSUE TITLE
Add support HHVM

### ISSUE THREAD

**Issue by njh** [easyrdf/easyrdf#225]
I added HHVM to Travis and discovered that the tests fail under it:
https://travis-ci.org/njh/easyrdf/jobs/45207836

Looks like we need to look into why EasyRdf doesn't work with HHVM.

**Comment by k00ni** [comment]
HHVM removed PHP support and may not run PHP code anymore. Therefore this issue should be closed.

**Comment by njh** [comment]
Thanks Konrad. I didn't know that HHVM doesn't support PHP anymore.
