### ISSUE TITLE
Add schema.org in the examples

### ISSUE THREAD

**Issue by ppKrauss** [easyrdf/easyrdf#237]
Hello, I am working with [schema.org](https://github.com/schemaorg) tools (where all is Python!) and was looking for a good PHP alternative (a framework for _HTML+RDFa_)... Can you add some SchemaOrg example here? The [current core is here](http://schema.org/docs/schema_org_rdfa.html).

I can enhance your example, or collaborate with a second one... From your example I can adapt [my ugly code](https://github.com/ppKrauss/schemaorg/blob/sdo-gozer/proposals/testing/issue280/updtRDF-CSV.php) to your framework.

**Comment by njh** [comment]
I agree it would be good to have a schema.org example. But what should the example demonstrate?

**Comment by ppKrauss** [comment]
Semantic scope can be [Person](http://schema.org/Person) or [Organization](http://schema.org/Organization)... [functionality](http://www.easyrdf.org/examples) can be any more advanced than HelloWorld, like serialisation (after parse transform in JSON/etc equivalents), or a [semantic query](http://www.easyrdf.org/examples/basic_sparql.php).

**Comment by njh** [comment]
Sorry, I don't really follow. How would the new schema.org example differ to the existing examples (other than swapping from foaf to schema.org) ?

What are you using schema.org for?
How could that be converted into a useful example?

**Comment by ppKrauss** [comment]
I'm also sorry: let me test some of your examples, then, I may show a draft for good SchemaOrg example... Need few days.

**Comment by k00ni** [comment]
Because there is no follow up this issue should be closed.
