### ISSUE TITLE
EasyRdf_Resource->label claims to return string, but returns EasyRdf_Literal

### ISSUE THREAD

**Issue by osma** [easyrdf/easyrdf#254]
The documentation (derived from the docstring) for the method EasyRdf_Resource->label claims that it will return a string, but actually it will return an EasyRdf_Literal instance:
http://www.easyrdf.org/docs/api/EasyRdf_Resource.html#method_label

The same applies for EasyRdf_Graph->label:
http://www.easyrdf.org/docs/api/EasyRdf_Graph.html#method_label

I noticed because Scrutinizer complains about code in my project that calls a getValue() on the result, which Scrutinizer thinks is a string but is actually not. See https://scrutinizer-ci.com/g/NatLibFi/Skosmos/issues/master/files/model/VocabularyCategory.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc#inspectioncomment-1482399456

I think the docstring for these two methods should simply be changed to reflect reality.

**Comment by njh** [comment]
I agree; the documentation should be corrected.  It probably pre-dates the EasyRdf_Literal class.
