### ISSUE TITLE
turtle parser slow on ubuntu 16.04 - php7

### ISSUE THREAD

**Issue by ecow** [easyrdf/easyrdf#267]
Hi,
in ubuntu 16.04 with php7 it seems that  turtle parser takes too much time to execute:

```
| Parser   | File size | Triple Count | Parse time (secs)  |
|----------|----------:|-------------:|-------------------:|
| RdfXml   |    140905 |         1190 |  0.047921895980835 |
| Turtle   |    112766 |         1190 |    31.923582077026 |
| Ntriples |    201754 |         1190 |  0.011803865432739 |
| JsonLd   |    126483 |         1190 |   0.16906905174255 |
```

N.B tests done  using the same RDF triples serialized with different representations

**Comment by njh** [comment]
The Turtle parser parses the file byte by byte, whereas the others make use of underlying parses (XML parser, Regex, JSON Parser).

So that might be it, but 30 seconds for 1000 triples does seem incredibly slow.

**Comment by ecow** [comment]
In ubuntu 14:04 (php 5) the parsing  time is comparable with xml. It seems that is  a problem related to php7 but I can investigate further now.

**Comment by vberkel** [comment]
I also ran into a similar problem where the turtle parse took 45 seconds, switching to ntriples under 1 second. Environments encountered on were 64bit Amazon Linux 2015.09 v2.0.6 running PHP 5.5 and macOSX 10.12 running PHP 5.6.

**Comment by k00ni** [comment]
Is this still an issue? There are many changes since 2016 and this issue might be solved.

**Comment by vberkel** [comment]
This should be closed, there was a PR https://github.com/easyrdf/easyrdf/pull/295 which resolves this issue.

**Comment by k00ni** [comment]
Thank you for the feedback.
