### ISSUE TITLE
Turtle parse error in converter

### ISSUE THREAD

**Issue by ecow** [easyrdf/easyrdf#277]
Hi,
strange turtle parsing error using the [converter](http://www.easyrdf.org/converter):

this generates one triple (ok):

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
<urn:a:b> foaf:primaryTopic [] .
```

this generates an error: (Error! Turtle Parse Error: expected an RDF value here, found ']' on line 3, column 1):

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
<urn:a:b> foaf:primaryTopic [
] .
```

**Comment by k00ni** [comment]
Can you test it again with the latest version please?

**Comment by njh** [comment]
I tested this using https://www.easyrdf.org/converter - running version 1.1.1 and it seems to be fixed.

Input:
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
<urn:a:b> foaf:primaryTopic [] .
```

Output (N-Triples):
```
<urn:a:b> <http://xmlns.com/foaf/0.1/primaryTopic> _:genid1 .
```
