### ISSUE TITLE
Would you support PSR-standardized RDF interfaces?

### ISSUE THREAD

**Issue by k00ni** [easyrdf/easyrdf#289]
Hi, i am currently working on a proposal for PHP-FIG to standardize interfaces representing RDF concepts like Triple, Statement and so on. The process just started, by proposing on the mailing list, but i hope it will go through. I welcome everbody to directly give me feedback on the proposal itself (via Github or the Google Group).

If this gets through, would you @njh be open to make EasyRdf compatible? As a first step, this could be done by providing a converter, which transforms EasyRdf-data directly into the new format. There is already code available (e.g. [here](https://github.com/SaftIng/Saft/blob/master/src/Saft/Addition/EasyRdf/Data/ParserEasyRdf.php#L168)), which can be used as a starting point. A pull request with a converter could be the result.

**Link to the working draft of the specification:** https://github.com/SaftIng/fig-standards/blob/psr-rdf/proposed/rdf/rdf.md
**Link to the proposal:** https://groups.google.com/forum/#!topic/php-fig/Z1dds-mBRrE

**Comment by njh** [comment]
Sound interesting.

Yes, implemented as a converter, that would be a good starting point.

**Comment by k00ni** [comment]
Closed, due outdated.
