### ISSUE TITLE
ZF 2 HTTP Client not working

### ISSUE THREAD

**Issue by cdekok** [easyrdf/easyrdf#305]
I needed zend http to do basic http authentication which the default http adapter doesn not seem to support.

According to this commit https://github.com/njh/easyrdf/commit/2de0339b3d1e5a2a557a51d8dc4220f935792661
It should work with zend http 2 but it calls the setHeaders method with invalid parameters.

```
Message: Invalid parameter headers passed
Stack trace:

#0 /var/www/openskos/vendor/easyrdf/easyrdf/lib/Sparql/Client.php(350): Zend\Http\Client->setHeaders('Accept', 'application/spa...')
```
The method setHeaders only accepts an array or Headers object.

**Comment by k00ni** [comment]
Hi @cdekok, maybe you are still interested in this issue. I fixed it in my EasyRdf fork.

Related issue: https://github.com/sweetyrdf/easyrdf/issues/9

It will be part of the next (test) version, but can be tested using `dev-master` (with composer).
