### ISSUE TITLE
Replace Sami for API documentation

### ISSUE THREAD

**Issue by njh** [easyrdf/easyrdf#322]
I [just upgraded](https://github.com/njh/easyrdf/commit/23864bebec97cdb8ac331243a573d2d67a74fa58) to Sami version 4.0.14. Which seems to work well and looks great. Sadly the project has been archived and is no longer supported 😞 

Possible alternatives:
- https://github.com/phpDocumentor/phpDocumentor
- https://github.com/theseer/phpdox
- Doxygen

I didn't find phpDocumentor very easy to use and the templates were a bit too fussy.
I haven't tried phpdox but the demo doesn't look very pretty: http://phpdox.de/demo/phpDox/index.xhtml

**Comment by williamdes** [comment]
New alternative https://github.com/code-lts/doctum#readme :tada:
