### ISSUE TITLE
Can't give array of properties to getLiteral or getResource

### ISSUE THREAD

**Issue by osma** [easyrdf/easyrdf#325]
According to the phpdocs, the getLiteral and getResource methods of Graph can be given an array of properties (phpdocs [here](https://github.com/easyrdf/easyrdf/blob/master/lib/Graph.php#L701) and [here](https://github.com/easyrdf/easyrdf/blob/master/lib/Graph.php#L720)):

>      * @param  string|array $property The name of the property (e.g. foaf:name)

However actually doing this causes an exception. I used this minimal example, adapted from the example on the easyrdf.org home page:

```php
$foaf = new EasyRdf\Graph("http://njh.me/foaf.rdf");
$foaf->load();
$me = $foaf->primaryTopic();
echo "My name is: ".$me->getLiteral(array('foaf:name','rdfs:label'))."\n";
```

gives this exception:

```
PHP Fatal error:  Uncaught InvalidArgumentException: $propertyPath should be a string or EasyRdf\Resource and cannot be null in /var/www/html/Skosmos/vendor/easyrdf/easyrdf/lib/Graph.php:595
Stack trace:
#0 /var/www/html/Skosmos/vendor/easyrdf/easyrdf/lib/Resource.php(396): EasyRdf\Graph->get('http://njh.me/', Array, 'literal', NULL)
#1 /var/www/html/Skosmos/test-easyrdf-get-array.php(8): EasyRdf\Resource->getLiteral(Array)
#2 {main}
  thrown in /var/www/html/Skosmos/vendor/easyrdf/easyrdf/lib/Graph.php on line 595
```

The problem is that both getLiteral and getResource directly call the `get` method which [checks the type of the `$propertyPath` parameter and doesn't accept an array](https://github.com/easyrdf/easyrdf/blob/master/lib/Graph.php#L613). It does, however, accept a path expression (a string with properties separated by pipe characters), so this works:

```php
echo "My name is: ".$me->getLiteral('foaf:name|rdfs:label')."\n";
```

I can see two obvious ways of fixing this:

1. Change the phpdoc so it doesn't say that you can pass an array as `$property` - i.e. don't advertise a feature that won't work anyway
2. Convert arrays into path expressions in getLiteral and getResource, before calling the `get` method

I can do a PR for either solution, but I'd appreciate opinions on which one to prefer.

**Comment by k00ni** [comment]
The API shouldn't be changed, but besides both solutions seem fine. (1.) seems to be the easiest one. How much code/effort would solution (2.) require? I am also thinking about the long term maintenance of this additional functionality.

**Comment by osma** [comment]
Thanks for your comment @k00ni! Either change is pretty much trivial (1 even more so than 2 - just removing a few characters from the phpdocs) and, in my opinion, not much of a maintenance burden.

I agree about not changing the API, but if the API advertises a feature that's actually broken (and hasn't worked for a long time, if ever), then I don't think removing that feature from the API is a big deal.

I will try to implement option 2, I think it should be trivial (a few lines of code). If it doesn't work out then option 1 could be the plan B.
