### ISSUE TITLE
Make Parser class abstract

### ISSUE THREAD

**Issue by njh** [easyrdf/easyrdf#328]
Serialiser class was made abstract in:
- ba4806e088b64f6918b66df52c2df5b0eb685777
- 5af0be7f32ca8fc3acb8aaf1ebe1e05a964dec0e

**Comment by k00ni** [comment]
What benefits do we get for making it abstract? 

Couldn't that be a backward compatibility break and therefore requires a new major version?

**Comment by k00ni** [comment]
> Couldn't that be a backward compatibility break and therefore requires a new major version?

Answer myself: It wouldn't be an API break, because it only had one public method which throws an exception if used directly (it had to be overridden).
