### ISSUE TITLE
Please add repository to https://scrutinizer-ci.com

### ISSUE THREAD

**Issue by k00ni** [easyrdf/easyrdf#329]
It provides good information about the code and changes during pull requests. Here is an example:

https://scrutinizer-ci.com/g/sweetyrdf/easyrdf/

**Comment by njh** [comment]
Thanks for the suggestion.

I haven't done any configuration but enabled the repo in Scrutinizer.
https://scrutinizer-ci.com/g/easyrdf/easyrdf/

**Comment by k00ni** [comment]
Thank you, will close this for now. We could reopen this issue, if there are further things to do with Scrutinizer.
