### ISSUE TITLE
Rework test environment (mostly use separate namespace, simplify code) - Add PHPStan

### ISSUE THREAD

**Issue by k00ni** [easyrdf/easyrdf#354]
I would like to use PHPStan for EasyRdf. Its a tool to check for dead code, wrong data type usages etc.

In my fork I already made the effort to adapt EasyRdf, so PHPStan can be used. Major obstacle was that EasyRdf uses the same namespaces for tests as for normal code. Because autoloading is required but tests use a different folder path no analysis was possible. In my PR https://github.com/sweetyrdf/easyrdf/pull/19 I made a lot of adaptions in the test folder to allow PHPStan. *Some adaptions can be ignored, because they concern other topics like Fuseki inclusion in tests.* Only a few adaptions in src are required, if I remember correctly.

With these changes EasyRdf applies for PHPStans level 1 of 7, which is a good start.

Furthermore, I hesitate when changing something in the test environment of EasyRdf. Also finding files can be hard, due to their opinionated placements.

Before making any efforts here, what do you think?

CC @njh, @osma, @zozlak

**Comment by osma** [comment]
I'm not familiar with PHPStan specifically, but I've suggested using other static analysis tools, many of which are provided as online services that are free for open source projects. Anything that improves the quality of code and discovers hidden bugs is good IMO.

**Comment by zozlak** [comment]
I have nothing against it.

**Comment by njh** [comment]
Getting PHPStan to work with EasyRdf sounds like a really good thing to do.
The more that can be automated, the better - particularly when reviewing Pull Requests.

I guess we should try and get as many of the open PRs closed as possible before working on this, because there are guaranteed to be lots of merge conflicts when changing so many files.

Does it replace phpcs?

**Comment by k00ni** [comment]
> I guess we should try and get as many of the open PRs closed as possible before working on this, because there are guaranteed to be lots of merge conflicts when changing so many files.

I agree.

> Does it replace phpcs?

No. I use PHP-CS-Fixer in my fork, but I didn't intend to replace phpcs with this.
