### ISSUE TITLE
Update 0.10.0-alpha.1 with  xml-chunked-parsing

### ISSUE THREAD

**Issue by akossentini** [easyrdf/easyrdf#376]
Hi,

I'm using 0.10.0-alpha.1 in old project and now i have problem with large XML.
I found that it's fixed, but merged to master, that require php7.1+
The project is running on php 5.6 and i can't upgrade php (need to check all project/modules...)
Can you please update tag  0.10.0-alpha.1 with xml-chunked-parsing branch ? (https://github.com/easyrdf/easyrdf/pull/370)  

Best Regards

**Comment by fehri-jawher** [comment]
i also need this please

Best Regards

**Comment by k00ni** [comment]
CC @njh 

There were *many* changes since 0.10.0-alpha 1 which also had to be back ported (including changes to support PHP 5.6 again). I as a co-maintainer don't have to time to do that, sorry.

**Comment by zozlak** [comment]
I don't see capacity for that as well and as a general rule I would be against supporting unsupported PHP versions (and support for PHP 5.6 ended two years ago).

**Comment by k00ni** [comment]
I am closing this for the following reasons:

* Supporting PHP 5.6 again would take a lot of work and reverts our improvements of the last months.
* Supporting old/outdated PHP versions is important for big projects, but as I could see myself this year, we don't have the man power to do that.
* Supporting legacy code is also a maintenance burden which blocks areas.

Feel free to fork this repository and add changes from #370 to the state of 0.10.0-alpha1.
