### ISSUE TITLE
[Feature] SPARQL INSERT using data from an EasyRdf Graph object.

### ISSUE THREAD

**Issue by deiu** [easyrdf/easyrdf#66]
Hey,

I know how the title sounds, but I'm wondering if you've ever thought about the possibility of adding a SPARQL INSERT/UPDATE method to EasyRdf_Grapht. Actually (just thinking out loud)...I wonder if it's nothing more than just iterating through the triples and inserting them.

**Comment by k00ni** [comment]
If there is no further feedback, this issue could be closed.

**Comment by deiu** [comment]
I'll close it, since it's pretty much dead. :)
